# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 5922

# 数据源配置
spring:
  #服务名称
  application:
    name: user-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/work_management?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password:
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        namespace: 00f9c098-31b9-435a-bc58-6430d05123d0


  # redis 配置
  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:5920/eureka



# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.web.**.dto,com.web.**.vo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml

# 接口文档
knife4j:
  enable: true
  openapi:
    title: 接口文档
    description: 第一次整合
    email:
    concat: 刘根裕
    url:
    version: v4.0
    license: Apache 2.0
    group:
      test1:
        group-name: 用户管理
        api-rule: package
        api-rule-resources:
          - com.web.controller


#日志输出
logging:
  level:
    com.web: DEBUG
    org.mybatis: DEBUG
    sql: DEBUG
